#!/usr/bin/env bash
# script that displays information about subdomains

domain="$1"
subdomain="$2"

if [[ -n "$subdomain" ]];

	then dig_result=$(dig +short "$subdomain.$subdomain" | awk '{print $1}')
	echo "The subdomain $subdomain is a A record and points to $dig_result"
else
	subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in "${subdomains[@]}";
		do
			dig_result=$(dig +short "$sub.$domain" | awk '{print $1}')
			echo "The subdomain $sub is a A record and points to dig_result"
		done
fi
	
