#!/usr/bin/env bash

# Update packages
sudo apt-get -y update
sudo apt-get upgrade -y

# Add HAProxy PPA
sudo apt-get install software-properties-common -y

# Install HAProxy
sudo apt-get install haproxy -y

# Configure HAProxy
balancer="
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 530641-web-01 100.25.3.175:80 check
    server 530641-web-02 54.90.44.227:80 check
"

# Backup the original configuration file
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Overwrite the configuration file with the new configuration
echo "$balancer" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy service
sudo service haproxy restart
